import About from "@/components/About";
import Education from "@/components/Education";
import Experience from "@/components/Experience";
import Projects from "@/components/Projects";
import Technologiess from "@/components/Technologiess";
import Text from "@/components/Text";

import { Box, Grid, Tooltip } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

const MENU = [
  {
    name: "Projects",
    component: <Projects />,
  },
  {
    name: "Technologies",
    component: <Technologiess />,
  },
  {
    name: "Experience",
    component: <Experience />,
  },
  {
    name: "Education",
    component: <Education />,
  },
  {
    name: "About",
    component: <About />,
  },
];

export default function Home() {
  const [value, setValue] = useState("one");

  const [menu, setMenu] = useState(MENU);

  const [selectedMenu, setSelectedMenu] = useState(MENU[0]);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  const handleMenu = (name) => {
    if (selectedMenu.name === name) {
      setSelectedMenu(MENU[0]);
    } else {
      const selected = MENU.find((m) => {
        return m.name === name;
      });

      setSelectedMenu(selected);
    }
  };

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <Box sx={{ display: "flex", justifyContent: "center" }}>
            <Box
              display="flex"
              flexDirection="column"
              padding={2}
              sx={{
                width: "450px",
                display: "flex",
                justifyContent: "center",
              }}
            >
              <img
                src="/sam3.jpg"
                height="80"
                width="80"
                style={{
                  objectFit: "cover",
                  borderRadius: "50%",
                  marginBottom: "15px",
                }}
              />
              <div
                style={{
                  marginBottom: "5px",
                  fontSize: "24px",
                  fontWeight: "bolder",
                }}
              >
                Syams Syair Ramadhan
              </div>

              <div
                style={{
                  display: "flex",
                  gap: "5px",
                  fontSize: "14px",
                  marginBottom: "5px",
                  color: "grey",
                }}
              >
                <Text variant="secondary-2">23</Text>
                <div> | </div>
                <Text variant="secondary-2">Web Developer</Text>
                <div> | </div>
                <Text variant="secondary-2">Bandung</Text>
              </div>

              <p style={{ marginBottom: "15px" }}>
                Interested in designing and developing web applications that are
                both visually stunning and fully functional
              </p>

              {/* */}

              <Grid container sx={{ marginBottom: "15px" }}>
                <Grid item xs={6}>
                  <div style={{ fontWeight: "bolder" }}>Projects</div>
                  <div>5+ </div>
                </Grid>
                <Grid item xs={6}>
                  <div style={{ fontWeight: "bolder" }}>Experience</div>
                  <div>1 year</div>
                </Grid>
              </Grid>

              <div
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  alignItems: "center",
                  gap: "5px",
                }}
              >
                {menu.map((m, index) => {
                  return (
                    <>
                      <div
                        style={{
                          backgroundColor:
                            selectedMenu.name === m.name ? "black" : "white",
                          padding: "5px 10px",
                          borderRadius: "20px",
                          cursor: "pointer",
                          border: "1px solid #e8e8e8",
                          color:
                            selectedMenu.name === m.name ? "white" : "black",
                        }}
                        onClick={() => handleMenu(m.name)}
                      >
                        {m.name}
                      </div>
                    </>
                  );
                })}
              </div>

              {/* */}

              <div style={{ marginTop: "10px" }}>{selectedMenu.component}</div>
            </Box>
          </Box>
        </section>
      </main>
    </>
  );
}
